name: Deploy to Firebase Hosting on Merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build App with Vite
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

     - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --site pixelpop-cd075 --project pixelpop-cd075
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIXELPOP_CD075 }}'
